name: 'IM Notification'
description: 'Sending a message to your social platform'
branding:
  icon: send
  color: orange
inputs:
  plat_type: 
    description: 'Which social platform to notify'
    required: true
    default: 'Lark'
  notify_title:
    description: 'It will be used as the head title of the notification.'
    required: false
    default: 'Project Updated'
  notify_message:
    description: 'It will be used as the content of the notification.'
    required: false
    default: ''
outputs:
  msg: # id of output
    description: 'The msg and code we sended to you'
runs:
  using: 'node12'
  main: './dist/min/index.js'